### POST NEW USER REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test@example.com",
    "firstName": "Test",
    "lastName": "User",
    "password": "Password@123"  
    
}


### POST USER LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Password@123"  
}

### POST RESET PASSWORD
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
    "email": "test@example.com",
    "newPassword": "Password@12"  
}

### POST CREATE ASSET
POST http://localhost:3000/api/asset/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoia2FtYWxAZ21haWwuY29tIiwiaWF0IjoxNzY3MzM1ODI4LCJleHAiOjE3NjczMzk0Mjh9.-_t_nFpewMBHcDw90TxHhIYNUMkNpOCp_hmQ3RNKVHA


{
    "title": "React boilerplate",
    "description": "A simple new react boilerplate done in 2024 version 21",
    "link": "https://www.react.com",
    "mac":"Mac 10"
}


### GET ALL ASSETS
GET http://localhost:3000/api/asset/all


### GET ASSET BY MAC
GET http://localhost:3000/api/asset/Mac 1


### DELETE ASSET BY ID
DELETE http://localhost:3000/api/asset/1


### UPDATE ASSET BY ID
PATCH http://localhost:3000/api/asset/2
Content-Type: application/json

{
    "mac":"Mac 3"
    
}
