### POST NEW USER REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test@example.com",
    "firstName": "Test",
    "lastName": "User",
    "password": "Password@123"  
    
}


### POST USER LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Password@123"  
}

### POST CREATE ASSET
POST http://localhost:3000/api/asset/create
Content-Type: application/json

{
    "title": "React boilerplate",
    "description": "A simple react boilerplate",
    "link": "www.react.com",
    "mac":"Mac 3"
}

### GET ALL ASSETS
GET http://localhost:3000/api/asset/all


### GET ASSET BY MAC
GET http://localhost:3000/api/asset/Mac 1


### DELETE ASSET BY ID
DELETE http://localhost:3000/api/asset/1


### UPDATE ASSET BY ID
PATCH http://localhost:3000/api/asset/2
Content-Type: application/json

{
    "mac":"Mac 3"
    
}
